on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20.12.0
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.0"

      - name: 🔨 Build Project
        run: |
          cd client
          npm install
          npx next build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.REACT_SERVER }}
          username: ${{ secrets.REACT_USER }}
          password: ${{ secrets.REACT_PWD }}
          protocol: ${{ secrets.REACT_PROTOCOL }}
          server-dir: /